frontend:
  replicaCount: 3
  image:
    repository: myrepo/ecommerce-frontend
    tag: "1.2.3"  
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: "200m"     
      memory: "256Mi"  
    limits:
      cpu: "1"       
      memory: "1Gi"   
  
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 20    
    targetCPUUtilizationPercentage: 60 
  
  pdb:
    enabled: true
    minAvailable: 2  


backend:
  replicaCount: 4
  image:
    repository: myrepo/ecommerce-backend
    tag: "2.1.5"    
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    requests:
      cpu: "500m"      
      memory: "512Mi" 
    limits:
      cpu: "2"       
      memory: "2Gi"
  
  hpa:
    enabled: true
    minReplicas: 4
    maxReplicas: 25 
    targetCPUUtilizationPercentage: 55  
  
  pdb:
    enabled: true
    minAvailable: 2  

ingress:
  enabled: true
  
  alb:
    scheme: internet-facing
    targetType: ip
    listenPorts: '[{"HTTP":80},{"HTTPS":443}]'
    certArn: "arn:aws:acm:ap-southeast-1:000000000000:certificate/00000000-0000-0000-0000-000000000000"
  
  hosts:
    - host: shop.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 3000

        - path: /api
          pathType: Prefix
          service: backend    
          port: 8080
        
