replicaCount: 2

image:
  repository: myrepo/my-go
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "200m"     
    memory: "256Mi"  
  limits:
    cpu: "1"       
    memory: "1Gi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

ingress:
  enabled: true
  className: alb
  hosts:
    - host: my-go.com
      paths:
        - path: /
          pathType: Prefix
  alb:
    scheme: internet-facing
    targetType: ip
    listenPorts: '[{"HTTP":80},{"HTTPS":443}]'
    certArn: arn:aws:acm:region:account:certificate/12345678
